engines:
    eslint:
        enabled: true
        channel: "eslint-3"
    csslint:
        enabled: true
ratings:
    paths:
        - "**.js"
        - "**.css"
exclude_paths:
    - "cmv/**/*"
    - "**/**.min.css"
    - "**/**.min.js"